---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: test-cluster-virtual-aci
  namespace: assisted-installer
spec:
  clusterDeploymentRef:
    name: test-cluster-virtual
  imageSetRef:
    name: openshift-v4.8.0
  networking:
    clusterNetwork:
      - cidr: "10.128.0.0/14"
        hostPrefix: 23
    serviceNetwork:
      - "172.30.0.0/16"
    machineNetwork:
      - cidr: "192.168.0.0/24"
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: 'REDACTED SSH KEY'
